config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'restaurants#index'
  resources :restaurants, only: %i[index show new create] do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
# frozen_string_literal: true

# Restaurant
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category,
            inclusion: { in: %w[chinese italian japanese french belgian] }

  def self.categories
    %w[chinese italian japanese french belgian]
  end

  def reviews_sort_date
    reviews.reverse
  end
end

app/models/review.rb
# frozen_string_literal: true

# Review
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating,  inclusion: { in: [*(0..5)] },
                      numericality: { only_integer: true }

  def self.rating_range
    [[5], [4], [3], [2], [1]]
  end

  def date
    created_at.strftime('%d/%m/%Y - %H:%M')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
# frozen_string_literal: true

# Restaurant Controller
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: :show

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number,
                                       :category)
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

# Review Controller
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]
  def new
    @review = Review.new
  end

  def create
    @review = @restaurant.reviews.build(review_params)

    if @review.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
     <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
    <%= link_to 'Restaurants',root_path, class: "navbar-brand"  %>
  </nav>
  <main class="container">
    <%= yield %>
  </main>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant, :html=> { class: 'form' } do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant.categories %>
  <div class="actions text-right">
    <%= f.submit "Create", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<header class="header">
  <h1>Restaurants</h1>
</header>

<div class="row">
  <%@restaurants.each do |restaurant|%>
    <div class="col-xs-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.2)), url('https://source.unsplash.com/800x450/?restaurants');">
        <h2 class="card-header"><%= restaurant.name %></h2>
        <%= link_to  '', restaurant, class: "card-link" %>
      </div>
    </div>
 <%end %>
</div>

<%= link_to raw('<i class="fas fa-plus"></i>'), new_restaurant_path, class: "btn flat-button" %>

app/views/restaurants/new.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <header class="header">
      <h1>New Restaurant </h1>
      <div class="actions text-right">
        <%= link_to raw('<i class="fas fa-chevron-left"></i> Back'), restaurants_path %>
      </div>
    </header>
    <%= render 'form', restaurant: @restaurant %>
  </div>
</div>

app/views/restaurants/show.html.erb
<header class="header">
  <div class="header-body"> <h1><%= @restaurant.name %></h1>
    <p><%= @restaurant.category %></p>
  </div>
  <div class="actions text-right">
    <%= link_to raw('<i class="fas fa-chevron-left"></i> Back'), restaurants_path %>
  </div>
</header>

<div class="info">
  <p><i class="fas fa-phone"></i> <%= @restaurant.phone_number %></p>
  <p><i class="fas fa-map-marker-alt"></i> <%= @restaurant.address %></p>
</div>
<iframe class="map" id="gmap_canvas" src="https://maps.google.com/maps?q=<%= @restaurant.address %>&t=&z=20&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>


<section class="review">
  <h2>Reviews</h2>
  <%= render '/reviews/form', restaurant: @restaurant, review: @review%>
  <ul class="list">
    <% @restaurant.reviews_sort_date.each do |review| %>
      <li>
        <div class="list-body">
          <span><%= review.date %></span>
          <p><%= review.content%></p>
        </div>
        <div>
          <%5.times do |i| %>
            <i class="start <%= i <= review.rating ? 'fas': 'far'%> fa-star"></i>
          <% end %>
        </div>
        </li>
    <%end %>
  </ul>
</section>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] , :html=> { class: 'form' } do |f| %>
  <div class="stars">
    <%= f.collection_radio_buttons :rating,  Review.rating_range, :first, :first, item_wrapper_tag: false, boolean_style: :inline do |b| %>
    <%= b.radio_button + b.label {''} %>
    <% end %>
  </div>
  <%= f.input :content,  label: false%>
  <div class="actions text-right">
    <%= f.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reviews/new.html.erb
<header class="header">
  <div class="header-body">
    <h1>New Review for <%= @restaurant.name %></h1>
  </div>
  <div class="actions text-right">
    <%= link_to raw('<i class="fas fa-chevron-left"></i> Back'), @restaurant %>
  </div>
</header>

<section class="review">
  <%= render 'form', restaurant: @restaurant, review: @review %>
</section>